# Hadolint configuration for Docker security scanning
# Ensures 10/10 security score for authentication service

rules:
  # Critical security rules (error level)
  DL3002: error  # Do not switch back to root user
  DL3008: error  # Pin package versions in apt
  DL3009: error  # Delete the apt-get lists after installing
  DL3015: error  # Avoid additional packages by specifying --no-install-recommends
  DL3018: error  # Pin package versions in apk add
  DL3025: error  # Use arguments JSON notation for CMD and ENTRYPOINT
  DL3026: error  # Use only an allowed registry in the FROM image
  DL3027: error  # Do not use apt as it is meant to be an end-user tool
  DL3059: error  # Multiple consecutive RUN instructions

  # Supply chain security
  DL3028: error  # Pin versions in gem install
  DL3029: error  # Do not use --platform flag with FROM
  DL3030: error  # Use the -y switch to avoid manual input

  # Information disclosure prevention
  DL3003: error  # Use WORKDIR to switch to a directory
  DL3020: error  # Use COPY instead of ADD for files and folders
  DL3032: error  # yum clean all missing after yum command
  DL3033: error  # Specify version with yum install
  DL3034: error  # Non-interactive switch missing from zypper command
  DL3035: error  # Do not use zypper dist-upgrade
  DL3036: error  # Specify version with zypper install
  DL3037: error  # Specify version with zypper install
  DL3040: error  # dnf clean all missing after dnf command
  DL3041: error  # Specify version with dnf install
  DL3042: error  # Avoid cache directory with dnf install
  DL3045: error  # COPY --from should reference a previously defined FROM alias
  DL3046: error  # useradd without flag -l and high UID will result in excessively large Image
  DL3047: error  # wget without flag --progress will result in excessively bloated build logs
  DL3048: error  # Invalid label key
  DL3049: error  # Label instruction should not be used
  DL3050: error  # Superfluous label instruction
  DL3051: error  # Label instruction is missing
  DL3052: error  # Label instruction should be specified
  DL3053: error  # Label instruction should be before any RUN instruction
  DL3055: error  # Label instruction should use double quotes
  DL3056: error  # Label instruction is duplicate
  DL3057: error  # HEALTHCHECK instruction missing
  DL3058: error  # Label instruction should not be used

  # Best practices (warning level for non-critical)
  DL3006: warning  # Always tag the version of an image explicitly
  DL3007: warning  # Using latest is prone to errors
  DL3010: warning  # Use ADD for extracting archives into an image
  DL3011: warning  # Valid UNIX ports range from 0 to 65535
  DL3012: warning  # Multiple HEALTHCHECK instructions
  DL3013: warning  # Pin versions in pip
  DL3014: warning  # Use the -y switch to avoid manual input
  DL3016: warning  # Pin versions in npm
  DL3017: warning  # Do not use apk upgrade
  DL3019: warning  # Use the --no-cache switch to avoid the need to use --update
  DL3021: warning  # COPY with more than 2 arguments requires the last argument to end with /
  DL3022: warning  # COPY --from should reference a previously defined FROM alias
  DL3023: warning  # COPY --from cannot reference its own FROM alias
  DL3024: warning  # FROM aliases should be unique

# Trusted registries for supply chain security
trusted-registries:
  - docker.io
  - gcr.io
  - ghcr.io
  - registry-1.docker.io
  - index.docker.io
  - quay.io

# Allowed base images (security-audited)
allowed-registries:
  - gcr.io/distroless
  - docker.io/library
  - oven

# Security-focused ignored rules (acceptable for distroless)
ignored:
  - SC2035  # Use ./*glob* - False positive for COPY bun.lockb
  # DL3006: We intentionally pin specific versions
  # DL3007: Not using latest tag
  # DL3059: Multiple RUN is acceptable in multi-stage builds for optimization

# Override specific checks that don't apply to distroless
override:
  # Distroless images don't have package managers, so version pinning doesn't apply
  error: []
  warning: []
  info: []
  style: []