name: 'Setup Docker Buildx with Enhanced Caching'
description: 'Setup Docker Buildx with optimized caching strategy'
inputs:
  registry:
    description: 'Docker registry URL'
    required: true
  username:
    description: 'Docker registry username'
    required: false
  password:
    description: 'Docker registry password'
    required: false
  login:
    description: 'Whether to login to Docker registry'
    required: false
    default: 'false'

outputs:
  buildx-name:
    description: 'Buildx builder name'
    value: ${{ steps.buildx.outputs.name }}

runs:
  using: 'composite'
  steps:
    - name: Log in to Docker registry
      if: inputs.login == 'true' && inputs.username != '' && inputs.password != ''
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: cloud
        endpoint: "zx8086/cldbuild"

    - name: Display Docker info
      shell: bash
      run: |
        echo "Docker version: $(docker --version)"
        echo "Buildx version: $(docker buildx version)"
        echo "Builder name: ${{ steps.buildx.outputs.name }}"
        echo "Login status: ${{ inputs.login }}"